# Default values for vmware-cloud-director.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

installFirstCell:
  enabled: true

installAdditionalCell:
  enabled: false

#storageClass: iscsi
#pvcCapacity: 1Gi

vcdNfs:
  server: 10.92.124.20
  mountPath: /mnt/nvme/vcd-k8s

vcdSystem:
  user: administrator
  password: Vmware1!
  email: admin@domain.local
  systemName: VCD
  installationId: 1

postgresql:
  dbHost: postgresql.vmware-cloud-director.svc.cluster.local
  dbName: vcloud
  dbUser: vcloud
  dbPassword: Vmware1!

# Availability zones in deployment.yaml are setup for TKG and must match VsphereFailureDomain and VsphereDeploymentZones
availabilityZones:
  enabled: false

httpsService:
  type: LoadBalancer
  port: 443

consoleProxyService:
  port: 8443

publicAddress:
  uiBaseUri: https://vcd-k8s.vmwire.com
  uiBaseHttpUri: http://vcd-k8s.vmwire.com
  restapiBaseUri: https://vcd-k8s.vmwire.com
  restapiBaseHttpUri: http://vcd-k8s.vmwire.com
  consoleProxy: vcd-vmrc.vmwire.com

image:
  repository: harbor.vmwire.com/library/centos-vcd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

tls:
  certFullChain: |-
    -----BEGIN CERTIFICATE-----
    MIIFHTCCBAWgAwIBAgISBIJysUrRaovnCD2Yml3AbkUFMA0GCSqGSIb3DQEBCwUA
    MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
    EwJSMzAeFw0yMjAxMDMxMzMzMzRaFw0yMjA0MDMxMzMzMzNaMBcxFTATBgNVBAMM
    DCoudm13aXJlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALr6
    awanLTejnnCYs2yTKBDi06z35/S0/puulh5ouVjmxDD8MuHVINxNolNhGLNI686H
    bKk5M8pxBQav2Lt1wm2F1ovMQZzMd6nddgUzX4Ceu9XtJxJRkU5FAar3spPCiUip
    Nl14PKIYl2xqV9qh2HrRgGPB6TmRtgPXVzwWMHh0Ih+9nmMs7iNhZKgF3PvS8Yfy
    FVcwtGkpas17O2zlPKx7UGUFEnmmn90E36QqwnB3r8ahzcGNrrEkPX2hDo2bbL3e
    KERqRXXV+IevMHGvCZLxeyebXJYWGi0Nr4K6YtprD/e2WV6juhaJejU5tdupvjKW
    I15jOLBFGaVbpYjnVG0CAwEAAaOCAkYwggJCMA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUeE+7jf25OD4jjbkShfCutj5Wp6EwHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA
    5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMu
    by5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8w
    FwYDVR0RBBAwDoIMKi52bXdpcmUuY29tMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcG
    CysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5
    cHQub3JnMIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHYA36Veq2iCTx9sre64X04+
    WurNohKkal6OOxLAIERcKnMAAAF+IFwbNAAABAMARzBFAiEA78anStClKBHbuLW+
    D9oIbrzGf0o+YJNyVXGnRhjGjJACICuvhKL4u4+ppex4/xBFzgzraRfn2MxUoCMn
    EVfFBrLGAHUAKXm+8J45OSHwVnOfY6V35b5XfZxgCvj5TV0mXCVdx4QAAAF+IFwb
    MQAABAMARjBEAiB0fNvilCgcMWFaSIUOEP6tmsa9UdcMmhqyHFfQb5LQ6AIgGIzu
    jDZz0sj8GeOeVz+kPxsZKfcpRFs0VLVv9w5GYQ4wDQYJKoZIhvcNAQELBQADggEB
    AKylgBrlypQNJlq0EQicYfWDI3oktEN+UL4Wihk9A6oWSS7fBdOEPtj3tnQ48d/n
    t8o8Ts3XJt3tBZ/Hn6IeBkhz4SZviorewOj+qY9e8mTXCwODhKPPlKqGRJjEvKOb
    A8jbW8wtc0m5WJYcE6epGbXfmLM5eWMer/fAcZGsL1CriOvxkpIXBypIgpbZpKM9
    r4z+S8jiJoVNZu9h4NGFclcVldg/JoYFECoGoJzOFc51h00wHmv5a4Rt9UVezkYB
    dF0HrNhZd8+fhBGXw29gmap8aoAiUlAvw1PYwU8jU+O+SQlEXgkZV67VPC1OqaJM
    d43kMDHIRT85BeD5st5OoM4=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
    WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
    R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
    sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
    NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
    Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
    /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
    AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
    Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
    FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
    AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
    Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
    gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
    PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
    ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
    CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
    lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
    avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
    yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
    yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
    hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
    HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
    MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
    nLRbwHOoq7hHwg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
    WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
    ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
    h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
    0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
    A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
    T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
    B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
    B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
    KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
    OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
    jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
    qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
    rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
    hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
    ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
    3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
    NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
    ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
    TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
    jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
    oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
    4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
    mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
    emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
    -----END CERTIFICATE-----
  certKey: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6+msGpy03o55w
    mLNskygQ4tOs9+f0tP6brpYeaLlY5sQw/DLh1SDcTaJTYRizSOvOh2ypOTPKcQUG
    r9i7dcJthdaLzEGczHep3XYFM1+AnrvV7ScSUZFORQGq97KTwolIqTZdeDyiGJds
    alfaodh60YBjwek5kbYD11c8FjB4dCIfvZ5jLO4jYWSoBdz70vGH8hVXMLRpKWrN
    ezts5Tyse1BlBRJ5pp/dBN+kKsJwd6/Goc3Bja6xJD19oQ6Nm2y93ihEakV11fiH
    rzBxrwmS8Xsnm1yWFhotDa+CumLaaw/3tlleo7oWiXo1ObXbqb4yliNeYziwRRml
    W6WI51RtAgMBAAECggEANEOxTO/H/Oh4bkLQzIWpymaNAqldJhK9pKi9f4yIWqhO
    qN6mHmgjwlDVEfdvHxZAC7/hCMBbkLfczsyyiVvWWCT0HqmeoYSp4kpsJfIBPQOh
    v5+Fr2IrerRhTffk69aR50SdVK06TZkQIpbrLcrVpycOe1QFrDjlptc3pC0TqWda
    naX7GF2Iggp7pOPKeODH1yE3PM3hVMKPkoYXg59RU2WKJLlPIqy6qrUZeQyXNbyT
    CUyj9k5BUuzH6n0fOSPoDSdzFkDYkgHMTtaSTA/z0y2d2wl6hZ4ZgGmS5RFs3/Tm
    GMayFxldAcgIiiskU04aE6TMw7Kh6mA2bVkv3TZfwQKBgQDcpAlIfVdWbwLYMnHE
    WEMpLT2X5XdW5ZBpJdETFQEzyW5zdaBxOTHQaGk4XoKVMObdieptc/k/9QQGehQx
    M+DuXTM1y/e5M3MfgsPeuCVOoNkoyT1idg6u7rKnTRaKu6ap+1MPELJ9RZ+EGjk/
    G5FurI34ioC76JeQEnyEc6wF8QKBgQDY8VkSPfojSddkH51phz7jSNhCf88NSobu
    xi0DzchS6gaC0s8MUzncY8zFfzszEjURQ6Njj1O8SooEvlyWKRE3lOXN/LCONC7N
    U9z6vPx6GhWDLDGZmfnuipmJNrYqaToQPhXNnMClgu9vVPyZmMAnXT3r9pBkbBY5
    PXbnaxaKPQKBgQC33QZTXwfp4iZXrWm6ueZ1qNqb+r+BLVozFS1uHmHbGu+szYe+
    8m99gZS1QaTF2HN6h9RQE4XQc0hAcXjkK5w0ZnwnR2qO7b3ws1KwBXopVMbCQzih
    FUpVIlrEKewv/gH7wpDLjBmBZQRx3Dx6R2ng9XB1fk2ayU+L4qva4F2osQKBgDP6
    L1MVklbeHEMa6AYep0yhaV8VbDBNCOMwjBx7M2HaPFEf3Qeg8R4Cs08mWrKzzA8k
    24LBFljoqwTT7y7zC/L7M8wUnOCVVBlR3IIewYcntLvG3ONmZuFmR77+Ysrqh0TY
    +zRWODnvkxpjjFnopTFJP8rHOnU1CGYSeeicWbwpAoGAG5S2ZBD6qbaDmeFp+Hwv
    6+W5tTReyYxPquM7KdB0K9SVfIGacrPudKz+WUbdXF+ssVASOm7zuHQUt0hTC3dx
    tgKKaVGG842wlcWaXVw/TU+ckuI/E8Apow4SlexOK8uj5du3P3v/rLrpqkbM0QQU
    ihiOIfvNikaYUcgQVxpNDvs=
    -----END PRIVATE KEY-----

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


