apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vmware-cloud-director.fullname" . }}
  labels:
    {{- include "vmware-cloud-director.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
        storage: {{ .Values.pvcCapacity }}