apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmware-cloud-director.fullname" . }}
  labels:
    {{- include "vmware-cloud-director.labels" . | nindent 4 }}
spec:
  type: {{ .Values.httpsService.type }}
  ports:
    - port: {{ .Values.httpsService.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.consoleProxyService.port }}
      targetPort: 8443
      protocol: TCP
      name: console-proxy
  selector:
    {{- include "vmware-cloud-director.selectorLabels" . | nindent 4 }}
