apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-configmap
data:
  cert.pem: |-
    {{ .Values.tls.certFullChain | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: key-configmap
data:
  cert.key: |-
    {{ .Values.tls.certKey | nindent 4 }}